//
//  AppRootPresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppRootPresentationLogic
{
  func presentSomething(response: AppRoot.Something.Response)
}

class AppRootPresenter: AppRootPresentationLogic
{
  weak var viewController: AppRootDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AppRoot.Something.Response)
  {
    let viewModel = AppRoot.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
