//
//  AppRootModels.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AppRoot
{
  // MARK: Use cases
}

enum PriceType: String {
    case BTC
    case USD
    case ETH
    case AUD

    var images: UIImage {
        switch self {
        case .BTC: return UIImage(named: "bitcoinImage")!
        case .USD: return UIImage(named: "dollarImage")!
        case .ETH: return UIImage(named: "ethImage")!
        case .AUD: return UIImage(named: "audImage")!
        }
    }
}
