//
//  AppRootRouter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa

@objc protocol AppRootRoutingLogic {
    func routeToDogeHome()
    func routeToChartHome()
}

protocol AppRootDataPassing {
    var dataStore: AppRootDataStore? { get }
}

class AppRootRouter: NSObject, AppRootRoutingLogic, AppRootDataPassing {
    weak var viewController: RootTabBarViewController?
    var dataStore: AppRootDataStore?
    var disposeBag = DisposeBag()

    var dogeHomeRouter: DogeHomeViewController
    var chartHomeRouter: ChartHomeViewController

    override init() {
        self.dogeHomeRouter = DogeHomeViewController()
        self.chartHomeRouter = ChartHomeViewController()
    }

    func setTabBarViewControllers() {
        dogeHomeRouter = DogeHomeViewController()
        dogeHomeRouter.tabBarItem = UITabBarItem(title: "", image: UIImage(systemName: "bitcoinsign.square"), selectedImage: UIImage(systemName: "bitcoinsign.square.fill"))
        dogeHomeRouter.tabBarItem.tag = 0

        chartHomeRouter = ChartHomeViewController()
        chartHomeRouter.tabBarItem = UITabBarItem(title: "", image: UIImage(systemName: "chart.bar"), selectedImage: UIImage(systemName: "chart.bar.fill"))
        chartHomeRouter.tabBarItem.tag = 1

        viewController?.viewControllers = [dogeHomeRouter, chartHomeRouter]
    }

    // MARK: Routing

    func routeToDogeHome() {
        let destinationDS = dogeHomeRouter.router!.dataStore!
        passDataToDogeHome(source: dataStore!, destination: destinationDS)
    }

    func routeToChartHome() {
        let destinationDS = chartHomeRouter.router!.dataStore!
        passChartToDogeHome(source: dataStore!, destination: destinationDS)
    }

    // MARK: Passing data

    func passDataToDogeHome(source: AppRootDataStore, destination: DogeHomeDataStore)
    {
        source.price.subscribe(onNext: { data in
            guard let data = data else { return }
            destination.price.accept(data)
        }).disposed(by: disposeBag)
    }

    func passChartToDogeHome(source: AppRootDataStore, destination: ChartHomeDataStore)
    {
        source.price.subscribe(onNext: { msg in
            destination.price.accept(msg)
        }).disposed(by: disposeBag)
    }
}
