//
//  AppRootInteractor.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa

protocol AppRootBusinessLogic {
    func connect()
}

protocol AppRootDataStore {
    var price: BehaviorRelay<Msg?> { get set }
}

class AppRootInteractor: AppRootBusinessLogic, AppRootDataStore {
    var price: BehaviorRelay<Msg?> = BehaviorRelay(value: nil)

    var presenter: AppRootPresentationLogic?
    var worker: AppRootWorker?

    var disposeBag = DisposeBag()

    func connect() {
        worker = AppRootWorker()
        worker?.connect()

        worker?.price.subscribe(onNext: { [weak self] msg in
            self?.price.accept(msg)
        }).disposed(by: disposeBag)
    }
}
