//
//  AppRootInteractor.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppRootBusinessLogic
{
  func doSomething(request: AppRoot.Something.Request)
}

protocol AppRootDataStore
{
  //var name: String { get set }
}

class AppRootInteractor: AppRootBusinessLogic, AppRootDataStore
{
  var presenter: AppRootPresentationLogic?
  var worker: AppRootWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AppRoot.Something.Request)
  {
    worker = AppRootWorker()
    worker?.doSomeWork()
    
    let response = AppRoot.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
