//
//  AppRootPresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppRootPresentationLogic
{
}

class AppRootPresenter: AppRootPresentationLogic
{
    weak var viewController: AppRootDisplayLogic?

}
