//
//  RootTabBarViewController.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppRootDisplayLogic: AnyObject {
}

class RootTabBarViewController: UITabBarController, AppRootDisplayLogic {
    var interactor: AppRootBusinessLogic?
    var router: (NSObjectProtocol & AppRootRoutingLogic & AppRootDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()

        connect()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = AppRootInteractor()
        let presenter = AppRootPresenter()
        let router = AppRootRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor

        router.setTabBarViewControllers()
        tabBarController?.delegate = self

        router.routeToDogeHome()
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    func connect() {
        interactor?.connect()
    }
}

extension RootTabBarViewController: UITabBarControllerDelegate {
    override func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        if item.tag == 0 {
            router?.routeToDogeHome()
        } else {
            router?.routeToChartHome()
        }
    }
}
