//
//  DogeHomePresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/10.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DogeHomePresentationLogic {
    func presentPrice(data: Msg)
}

class DogeHomePresenter: DogeHomePresentationLogic {
    weak var viewController: DogeHomeDisplayLogic?

    // MARK: Do something

    func presentPrice(data: Msg) {
        typealias DisplayedPrice = DogeHome.ConnectWebSocket.ViewModel.DisplayedPrice
        let displayedPrice = DisplayedPrice(msg: data)

        let viewModel = DogeHome.ConnectWebSocket.ViewModel(displayedPrice: displayedPrice)
        viewController?.displayPrice(viewModel: viewModel)
    }
}
