//
//  DogeHomeInteractor.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/10.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxRelay

protocol DogeHomeBusinessLogic {
    func connect()
}

protocol DogeHomeDataStore {
    var price: BehaviorRelay<Msg?> { get set }
}

class DogeHomeInteractor: DogeHomeBusinessLogic, DogeHomeDataStore {
    var price: BehaviorRelay<Msg?> = BehaviorRelay(value: nil)

    var presenter: DogeHomePresentationLogic?
    var worker: DogeHomeWorker?
    var disposeBag = DisposeBag()

    // MARK: Do something

    func connect() {
        price.subscribe(onNext: { [weak self] data in
            guard let data = data else { return }
            self?.presenter?.presentPrice(data: data)
        }).disposed(by: disposeBag)
    }
}
