//
//  ChartDetailInteractor.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/13.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartDetailBusinessLogic
{
  func doSomething(request: ChartDetail.Something.Request)
}

protocol ChartDetailDataStore
{
  //var name: String { get set }
}

class ChartDetailInteractor: ChartDetailBusinessLogic, ChartDetailDataStore
{
  var presenter: ChartDetailPresentationLogic?
  var worker: ChartDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChartDetail.Something.Request)
  {
    worker = ChartDetailWorker()
    worker?.doSomeWork()
    
    let response = ChartDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
