//
//  ChartDetailPresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/13.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartDetailPresentationLogic
{
  func presentSomething(response: ChartDetail.Something.Response)
}

class ChartDetailPresenter: ChartDetailPresentationLogic
{
  weak var viewController: ChartDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChartDetail.Something.Response)
  {
    let viewModel = ChartDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
