//
//  ChartDetailPresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/13.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartDetailPresentationLogic
{
    func presentPriceList(data: [Msg])
}

class ChartDetailPresenter: ChartDetailPresentationLogic
{
    weak var viewController: ChartDetailDisplayLogic?

    // MARK: Do something

    func presentPriceList(data: [Msg])
    {
        typealias DisplayedPrice = ChartDetail.ConnectWebSocket.ViewModel.DisplayedPrice

        let displayedPrices = data.map { DisplayedPrice(msg: $0) }
        let viewModel = ChartDetail.ConnectWebSocket.ViewModel(displayedPrices: displayedPrices)
        viewController?.displayPriceList(viewModel: viewModel)
    }
}
