//
//  ChartHomeRouter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/12.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol ChartHomeRoutingLogic
{
    func routeToChartDetail(priceBase: String)
}

protocol ChartHomeDataPassing
{
    var dataStore: ChartHomeDataStore? { get }
}

class ChartHomeRouter: NSObject, ChartHomeRoutingLogic, ChartHomeDataPassing
{
    weak var viewController: ChartHomeViewController?
    var dataStore: ChartHomeDataStore?
    var disposeBag = DisposeBag()

    // MARK: Routing

    func routeToChartDetail(priceBase: String) {
        let destinationVC = ChartDetailViewController()
        navigateToChartDetail(source: viewController!, destination: destinationVC)
        let destinationDS = destinationVC.router!.dataStore!
        passDataToChartDetail(source: dataStore!, destination: destinationDS, priceBase: priceBase)

    }

    // MARK: Navigation

    func navigateToChartDetail(source: ChartHomeViewController, destination: ChartDetailViewController) {
        source.present(destination, animated: false)
    }

    // MARK: Passing data

    func passDataToChartDetail(source: ChartHomeDataStore, destination: ChartDetailDataStore, priceBase: String) {
        source.bitcoinList.subscribe(onNext: { destination.bitcoinList.accept($0)} ).disposed(by: disposeBag)
        source.dolloarList.subscribe(onNext: { destination.dolloarList.accept($0)} ).disposed(by: disposeBag)
        source.audList.subscribe(onNext: { destination.audList.accept($0)} ).disposed(by: disposeBag)
        source.etherList.subscribe(onNext: { destination.etherList.accept($0)} ).disposed(by: disposeBag)
        destination.priceBase.accept(priceBase)
    }
}
