//
//  ChartHomePresenter.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/12.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartHomePresentationLogic {
    func presentPriceTableView(data: Msg)
}

class ChartHomePresenter: ChartHomePresentationLogic {
    weak var viewController: ChartHomeDisplayLogic?

    // MARK: Do something

    func presentPriceTableView(data: Msg) {
        typealias DispalyedPrice = ChartHome.ConnectWebSocket.ViewModel.DisplayedPrice
        let displayedPrice = DispalyedPrice(msg: data)
        let viewModel = ChartHome.ConnectWebSocket.ViewModel(displayedPrice: displayedPrice)
        viewController?.displayPriceList(viewModel: viewModel)
    }
}
