//
//  ChartHomeModels.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/12.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChartHome {
    // MARK: Use cases

    enum ConnectWebSocket {
        struct ViewModel {
            struct DisplayedPrice {
                var price: String
                var coinImage: UIImage
                var priceBase: String

                init(msg: Msg) {
                    self.price = msg.value ?? ""

                    var image: UIImage {
                        guard let priceBase = msg.priceBase else { return UIImage() }
                        if priceBase == "BTC" {
                            return PriceType.BTC.images
                        } else if priceBase == "USD" {
                            return PriceType.USD.images
                        } else if priceBase == "ETH" {
                            return PriceType.ETH.images
                        } else {
                            return PriceType.AUD.images
                        }
                    }
                    self.priceBase = msg.priceBase ?? ""
                    self.coinImage = image
                }
            }

            var displayedPrice: DisplayedPrice
        }
    }
}
