//
//  ChartHomeInteractor.swift
//  DogePay
//
//  Created by Victor Lee on 2023/03/12.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartHomeBusinessLogic
{
  func doSomething(request: ChartHome.Something.Request)
}

protocol ChartHomeDataStore
{
  //var name: String { get set }
}

class ChartHomeInteractor: ChartHomeBusinessLogic, ChartHomeDataStore
{
  var presenter: ChartHomePresentationLogic?
  var worker: ChartHomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChartHome.Something.Request)
  {
    worker = ChartHomeWorker()
    worker?.doSomeWork()
    
    let response = ChartHome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
